### ISSUE TITLE
Possible Fiber issue?

### ISSUE THREAD

**Issue by Max-Meldrum** [SparkyPotato/tracy_full#4]
https://github.com/SparkyPotato/tracy_full/blob/edab2ddd948212a235e2699b95a8c78688d915c6/src/future.rs#L52

Should there be a 2nd enter call here?

**Comment by SparkyPotato** [comment]
If the inner future also has a wrapped future somewhere in the call chain, that would switch the current thread's tracked fiber, so we need to switch back to the correct fiber before leaving.

Without the second enter call, I believe there were inconsistent traces or crashes, I don't remember which. Does it work without it on the latest version of Tracy?

**Comment by Max-Meldrum** [comment]
> If the inner future also has a wrapped future somewhere in the call chain, that would switch the current thread's tracked fiber, so we need to switch back to the correct fiber before leaving.
> 
> Without the second enter call, I believe there were inconsistent traces or crashes, I don't remember which. Does it work without it on the latest version of Tracy?

Right I see, thanks for the reply 😄  Yes I believe it works but I just wasn't sure whether it was being a redundant call or not.
